Repository meshtastic/web, pull requests merged in 2024-06, with the labels that each got.

#221 Map dark mode
  src/pages/Map.tsx
Labels: enhancement

#198 Use localStorage to store theme preference
  src/core/stores/appStore.ts
Labels: enhancement

#202 fix(Connect): disable connecting multiple times
  src/components/PageComponents/Connect/HTTP.tsx
Labels: enhancement

#244 update MQTT precision dropdown and encryption warning
  src/components/PageComponents/ModuleConfig/MQTT.tsx
Labels: enhancement

#165 Fix sorting on peers table
  src/components/generic/Table/index.tsx
Labels: bug, help wanted, minor

#213 Update biome, fix and enforce recommended rules
  .vscode/settings.json
  biome.json
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  src/components/CommandPalette.tsx
  src/components/DeviceSelector.tsx
  src/components/Dialog/DialogManager.tsx
  src/components/Dialog/QRDialog.tsx
  src/components/Dialog/RebootDialog.tsx
  src/components/Dialog/RemoveNodeDialog.tsx
  src/components/Dialog/ShutdownDialog.tsx
  src/components/Form/DynamicForm.tsx
  src/components/Form/DynamicFormField.tsx
  src/components/Form/FormInput.tsx
  src/components/Form/FormSelect.tsx
  src/components/Form/FormToggle.tsx
  src/components/PageComponents/Channel.tsx
  src/components/PageComponents/Config/LoRa.tsx
  src/components/PageComponents/Connect/BLE.tsx
  src/components/PageComponents/Connect/HTTP.tsx
  src/components/PageComponents/Connect/Serial.tsx
  src/components/PageComponents/Messages/ChannelChat.tsx
  src/components/PageComponents/ModuleConfig/DetectionSensor.tsx
  src/components/PageComponents/ModuleConfig/MQTT.tsx
  src/components/PageComponents/ModuleConfig/NeighborInfo.tsx
  src/components/PageComponents/ModuleConfig/Paxcounter.tsx
  src/components/PageLayout.tsx
  src/components/Sidebar.tsx
  src/components/Toaster.tsx
  src/components/UI/Button.tsx
  src/components/UI/Toast.tsx
  src/components/generic/Table/index.tsx
  src/core/hooks/useToast.ts
  src/core/stores/appStore.ts
  src/core/stores/deviceStore.ts
  src/core/subscriptions.ts
  src/core/utils/cn.ts
  src/pages/Config/DeviceConfig.tsx
  src/pages/Config/ModuleConfig.tsx
  src/pages/Map.tsx
  src/pages/Nodes.tsx
  src/validation/config/position.ts
  src/validation/moduleConfig/mqtt.ts
  vite.config.ts
Labels: bug, enhancement, major change
