Repository meshtastic/web, pull requests merged in 2024-09, with the labels that each got.

#288 Change 'powerScreenEnabled' config type to toggle
  src/components/PageComponents/ModuleConfig/Telemetry.tsx
Labels: bug, minor change

#289 GitHub Actions: Releases
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: enhancement, help wanted, major change, meta

#290 Rework disabled in DynamicForms
  src/components/Form/DynamicForm.tsx
  src/components/PageComponents/Config/Security.tsx
Labels: enhancement, minor change

#277 Update key generation
  package.json
  pnpm-lock.yaml
  src/components/Dialog/PkiRegenerateDialog.tsx
  src/components/Form/FormInput.tsx
  src/components/Form/FormPasswordGenerator.tsx
  src/components/PageComponents/Config/Security.tsx
  src/components/UI/Generator.tsx
  src/components/UI/Input.tsx
  src/core/utils/x25519.ts
Labels: enhancement, major change, parity

#293 Node List & DMs
  package.json
  pnpm-lock.yaml
  src/components/PageComponents/Config/LoRa.tsx
  src/components/PageComponents/Config/Security.tsx
  src/components/PageLayout.tsx
  src/pages/Messages.tsx
  src/pages/Nodes.tsx
  src/validation/config/lora.ts
Labels: enhancement, minor change, parity, protobuf

#269 Fix/static ip display
  src/components/PageComponents/Config/Network.tsx
  src/core/utils/ip.ts
  src/validation/config/network.ts
Labels: bug, minor change
