Repository meshtastic/web, pull requests merged in 2025-03, with the labels that each got.

#474 Added a notes field to Dynamic form informing users about BLE and Wifi use
  src/components/Form/DynamicForm.tsx
  src/components/PageComponents/Config/Bluetooth.tsx
  src/components/PageComponents/Config/Network.tsx
  src/components/PageComponents/Connect/Serial.tsx
Labels: enhancement

#458 feat: add error boundary
  bun.lock
  package.json
  public/images/chirpy.svg
  src/App.tsx
  src/PageRouter.tsx
  src/components/Form/DynamicForm.tsx
  src/components/PageComponents/Map/NodeDetail.tsx
  src/components/PageComponents/Messages/Message.tsx
  src/components/PageLayout.tsx
  src/components/UI/ErrorPage.tsx
  src/components/UI/Sidebar/SidebarSection.tsx
  src/components/UI/Typography/H1.tsx
  src/components/UI/Typography/H2.tsx
  src/components/UI/Typography/H3.tsx
  src/components/UI/Typography/H4.tsx
  src/components/UI/Typography/H5.tsx
  src/components/UI/Typography/Heading.tsx
  src/components/UI/Typography/P.tsx
  src/core/utils/github.ts
  src/index.css
  src/pages/Dashboard/index.tsx
Labels: enhancement, major change

#478 Fix Nodes page
  src/pages/Nodes.tsx
Labels: bug, minor change

#513 Position Precision Rework
  src/components/Form/DynamicForm.tsx
  src/components/PageComponents/Channel.tsx
Labels: bug

#516 feat: add error handling for key mismatch
  src/components/Dialog/DialogManager.tsx
  src/components/Dialog/RefreshKeysDialog/RefreshKeysDialog.test.tsx
  src/components/Dialog/RefreshKeysDialog/RefreshKeysDialog.tsx
  src/components/Dialog/RefreshKeysDialog/useRefreshKeysDialog.test.ts
  src/components/Dialog/RefreshKeysDialog/useRefreshKeysDialog.ts
  src/components/PageComponents/Connect/Serial.tsx
  src/components/PageComponents/Messages/ChannelChat.tsx
  src/components/PageComponents/Messages/Message.tsx
  src/components/PageComponents/Messages/MessageItem.tsx
  src/components/UI/Avatar.tsx
  src/components/UI/Button.tsx
  src/core/stores/deviceStore.ts
  src/core/subscriptions.ts
  src/pages/Messages.tsx
  src/pages/Nodes.tsx
  vite.config.ts
Labels: bug, enhancement

#500 Update style and wording of browser support for connection types
  src/components/Dialog/NewDeviceDialog.tsx
Labels: enhancement

#528 Refactor useBackupReminder hook
  src/components/KeyBackupReminder.tsx
  src/components/Toaster.tsx
  src/core/hooks/useKeyBackupReminder.tsx
  src/core/hooks/useLocalStorage.test.ts
  src/core/hooks/useToast.test.tsx
  src/core/hooks/useToast.ts
Labels: enhancement
