Repository meshtastic/web, pull requests merged in 2025-02, with the labels that each got.

#391 fix: Map Action Buttons key
  src/components/PageLayout.tsx
Labels: minor change

#349 feat: Add search functionality for nodes in Messages and Nodes pages
  src/pages/Messages.tsx
  src/pages/Nodes.tsx
Labels: enhancement, minor change

#390 fix: improve styling of messages
  src/components/PageComponents/Messages/ChannelChat.tsx
  src/components/PageComponents/Messages/Message.tsx
  src/components/PageComponents/Messages/MessageInput.tsx
  src/components/UI/Footer.tsx
  src/components/UI/Sidebar/sidebarButton.tsx
  src/pages/Messages.tsx
Labels: minor change

#394 Feat: Add MultiSelect component
  src/components/Form/DynamicFormField.tsx
  src/components/Form/FormMultiSelect.tsx
  src/components/Form/FormSelect.tsx
  src/components/PageComponents/Config/Position.tsx
  src/components/UI/MultiSelect.tsx
  src/core/hooks/usePositionFlags.ts
Labels: enhancement, minor change, parity

#285 Use window.location.host so that websites run on non-standard ports i…
  src/components/PageComponents/Connect/HTTP.tsx
Labels: enhancement, minor change

#411 feat: adding pluralizer util. fix: measurement unit in marker popup
  src/components/PageComponents/Map/NodeDetail.tsx
  src/core/utils/string.ts
Labels: enhancement, minor change

#416 fix: prevent empty/blank messages from being sent.
  src/components/PageComponents/Messages/MessageInput.tsx
Labels: bug, minor change

#409 Fixed map zooming when clicking on map marker. Fixed popup alignment to Map Marker
  src/components/PageComponents/Map/NodeDetail.tsx
  src/pages/Map.tsx
Labels: bug, enhancement

#423 feat: added text style chat messages
  src/components/PageComponents/Messages/ChannelChat.tsx
  src/components/PageComponents/Messages/Message.tsx
  src/components/PageComponents/Messages/MessageInput.tsx
  src/components/UI/Tooltip.tsx
Labels: enhancement, minor change

#307 [Feature request]: Nodes quick options
  package.json
  pnpm-lock.yaml
  public/devices/README.md
  public/devices/diy.svg
  public/devices/heltec-ht62-esp32c3-sx1262.svg
  public/devices/heltec-mesh-node-t114-case.svg
  public/devices/heltec-mesh-node-t114.svg
  public/devices/heltec-v3-case.svg
  public/devices/heltec-v3.svg
  public/devices/heltec-vision-master-e213.svg
  public/devices/heltec-vision-master-e290.svg
  public/devices/heltec-vision-master-t190.svg
  public/devices/heltec-wireless-paper-V1_0.svg
  public/devices/heltec-wireless-paper.svg
  public/devices/heltec-wireless-tracker-V1-0.svg
  public/devices/heltec-wireless-tracker.svg
  public/devices/heltec-wsl-v3.svg
  public/devices/nano-g2-ultra.svg
  public/devices/pico.svg
  public/devices/promicro.svg
  public/devices/rak-wismeshtap.svg
  public/devices/rak11310.svg
  public/devices/rak2560.svg
  public/devices/rak4631.svg
  public/devices/rak4631_case.svg
  public/devices/rpipicow.svg
  public/devices/seeed-sensecap-indicator.svg
  public/devices/seeed-xiao-s3.svg
  public/devices/station-g2.svg
  public/devices/t-deck.svg
  public/devices/t-echo.svg
  public/devices/t-watch-s3.svg
  public/devices/tbeam-s3-core.svg
  public/devices/tbeam.svg
  public/devices/tlora-c6.svg
  public/devices/tlora-t3s3-epaper.svg
  public/devices/tlora-t3s3-v1.svg
  public/devices/tlora-v2-1-1_6.svg
  public/devices/tlora-v2-1-1_8.svg
  public/devices/tracker-t1000-e.svg
  public/devices/unknown.svg
  public/devices/wio-tracker-wm1110.svg
  public/devices/wm1110_dev_kit.svg
  src/components/Dialog/DialogManager.tsx
  src/components/Dialog/LocationResponseDialog.tsx
  src/components/Dialog/NodeDetailsDialog.tsx
  src/components/Dialog/NodeOptionsDialog.tsx
  src/components/Dialog/TracerouteResponseDialog.tsx
  src/components/PageComponents/Map/NodeDetail.tsx
  src/components/PageComponents/Messages/TraceRoute.tsx
  src/components/UI/Accordion.tsx
  src/components/UI/Dialog.tsx
  src/components/generic/DeviceImage.tsx
  src/components/generic/Table/tmp/TimeAgo.tsx
  src/components/generic/TimeAgo.tsx
  src/components/generic/Uptime.tsx
  src/core/stores/appStore.ts
  src/core/stores/deviceStore.ts
  src/pages/Messages.tsx
  src/pages/Nodes.tsx
Labels: enhancement, major change

#250 add ability to enable/disable HTTPS connections
  src/components/PageComponents/Connect/HTTP.tsx
Labels: bug, minor change

#432 feat: update to tailwind 4.x
  index.html
  package.json
  postcss.config.cjs
  src/App.tsx
  src/PageRouter.tsx
  src/components/CommandPalette.tsx
  src/components/DeviceSelector.tsx
  src/components/Dialog/ImportDialog.tsx
  src/components/Dialog/NewDeviceDialog.tsx
  src/components/Dialog/QRDialog.tsx
  src/components/Form/DynamicForm.tsx
  src/components/PageComponents/Connect/BLE.tsx
  src/components/PageComponents/Connect/HTTP.tsx
  src/components/PageComponents/Connect/Serial.tsx
  src/components/PageComponents/Map/NodeDetail.tsx
  src/components/PageComponents/Messages/ChannelChat.tsx
  src/components/PageComponents/Messages/Message.tsx
  src/components/PageComponents/Messages/MessageInput.tsx
  src/components/PageComponents/Messages/TraceRoute.tsx
  src/components/PageLayout.tsx
  src/components/Sidebar.tsx
  src/components/ThemeSwitcher.tsx
  src/components/UI/Button.tsx
  src/components/UI/Checkbox.tsx
  src/components/UI/Command.tsx
  src/components/UI/Dialog.tsx
  src/components/UI/DropdownMenu.tsx
  src/components/UI/Footer.tsx
  src/components/UI/Generator.tsx
  src/components/UI/Input.tsx
  src/components/UI/Menubar.tsx
  src/components/UI/MultiSelect.tsx
  src/components/UI/Popover.tsx
  src/components/UI/Select.tsx
  src/components/UI/Sidebar/sidebarButton.tsx
  src/components/UI/Switch.tsx
  src/components/UI/Tabs.tsx
  src/components/UI/Toast.tsx
  src/components/UI/Typography/Code.tsx
  src/components/UI/Typography/P.tsx
  src/components/generic/Mono.tsx
  src/components/generic/Table/index.tsx
  src/components/generic/ThemeController.tsx
  src/components/generic/ThemeProvider.tsx
  src/core/hooks/useTheme.ts
  src/core/stores/appStore.ts
  src/index.css
  src/pages/Channels.tsx
  src/pages/Config/DeviceConfig.tsx
  src/pages/Config/ModuleConfig.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Map/index.tsx
  src/pages/Messages.tsx
  src/pages/Nodes.tsx
  tailwind.config.cjs
Labels: enhancement, dependencies, major change

#417 feat: switch to Vite 6.x
  package.json
  pnpm-lock.yaml
  rsbuild.config.ts
  src/components/DeviceSelector.tsx
  src/components/PageComponents/Connect/HTTP.tsx
  src/components/ThemeSwitcher.tsx
  src/components/UI/Button.tsx
  src/components/UI/Switch.tsx
  src/components/UI/Toast.tsx
  src/core/hooks/useTheme.ts
  src/core/stores/appStore.ts
  src/index.css
  vite.config.ts
Labels: enhancement, dependencies, major change
